version: '3.7'

networks:

  app-network:

volumes:

    app-volume:

services:

  public:
    build: ./public
    container_name: public
    networks:
      - app-network
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build: ./server
    container_name: server
    networks:
      - app-network
    ports:
      - "5000:5000"
    depends_on:
      - database
    

  database:
    image: mongo
    container_name: mongo
    networks:
      - app-network
    ports:
      - "27017:27017"
    volumes:
      - app-volume:/data/db

