name: Deploy with Docker Compose

on:
  push:
    branches:
      - main  # Change this to match your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH into Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        script: |
          cd /home/chat-app-react-nodejs
          git pull origin main

    - name: Docker Compose Up
      uses: docker/compose-cli@v1
      with:
        args: up -d
