name: Deploy with Docker Compose

on:
  push:
    branches:
      - main  # Change this to match your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH into Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        script: |
          cd /home/ubuntu/chat-app-react-nodejs
          git init
          #git remote add origin https://github.com/akurasy/chat-app-react-nodejs.git
          #git pull origin main
          echo running a docker-compose command
          cd /home/ubuntu/chat-app-react-nodejs
          docker-compose up -d
    #- name: Docker Compose Up
      #run: |
        #sudo su - ubuntu
        #echo running a docker-compose deployment
        #cd /home/ubuntu/chat-app-react-nodejs
        #docker-compose up -d
